name: Rsync Folders1
description: "Transfers the Hass.io folders (including backups) to a remote rsync server."
version: 2022.10-1
slug: rsync_folders1
init: false
startup: once
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

map:
  - config
  - addons
  - backup:rw
  - share
  - ssl
  - media

options:
  server: rsync-server
  port: 22
  target: hassio-backups
  username: user
  password: password
  auto_purge: 0
  ssh_enabled: true
  f_config: true
  f_addons: false
  f_backup: true
  f_share: false
  f_ssl: false
  f_media: false

schema:
  server: str
  port: int
  target: str
  username: str
  password: str
  auto_purge: int
  ssh_enabled: bool
  f_config: bool
  f_addons: bool
  f_backup: bool
  f_share: bool
  f_ssl: bool
  f_media: bool

